import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@/components/template/ToastContainer";

export const metadata: Metadata = {
  title: "GrupoKasama",
  icons: '/favicon.ico',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
